version: '3'
services:
  docker-draggonwell8:
    stdin_open: true
    tty: true
    image: terwer/draggonwell8:14.04
    container_name: docker-draggonwell8
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 22:22
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./code:/home/
      - ./bootjdk:/opt/java